pub mod browser;
pub mod colorpicker;
pub mod displaysettings;
pub mod filemanager;
pub mod personalize;
pub mod sysmon;
pub mod terminal;
pub mod textviewer;
pub mod usergui;
pub mod utilities;

pub use browser::BrowserApp;
pub use colorpicker::ColorPickerApp;
pub use displaysettings::DisplaySettingsApp;
pub use filemanager::{FileManagerApp, FileManagerOpenRequest};
pub use personalize::PersonalizeApp;
pub use sysmon::SysMonApp;
pub use terminal::TerminalApp;
pub use textviewer::TextViewerApp;
pub use usergui::UserGuiApp;
pub use utilities::UtilityApp;
