pub mod browser;
pub mod color_picker;
pub mod display_settings;
pub mod file_manager;
pub mod personalize;
pub mod system_monitor;
pub mod terminal;
pub mod text_viewer;
pub mod theme;
pub mod user_gui;
pub mod utilities;

pub use browser::BrowserApp;
pub use color_picker::ColorPickerApp;
pub use display_settings::DisplaySettingsApp;
pub use file_manager::{FileManagerApp, FileManagerOpenRequest};
pub use personalize::PersonalizeApp;
pub use system_monitor::{SysMonApp, SysMonRequest};
pub use terminal::TerminalApp;
pub use text_viewer::TextViewerApp;
pub use user_gui::UserGuiApp;
pub use utilities::UtilityApp;
