#!/usr/bin/env python3
"""Generate src/tls_roots.rs from a PEM CA bundle."""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import subprocess
import tempfile
from pathlib import Path


DEFAULT_BUNDLES = (
    "/etc/ssl/cert.pem",
    "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/certifi/cacert.pem",
)

PREFERRED_ROOTS = (
    "AAA Certificate Services",
    "ISRG Root X1",
    "DigiCert Global Root G2",
    "DigiCert Global Root G3",
    "DigiCert Global Root CA",
    "GTS Root R1",
    "GTS Root R2",
    "GTS Root R4",
    "Amazon Root CA 1",
    "Amazon Root CA 2",
    "GlobalSign Root CA",
    "GlobalSign Root R3",
    "USERTrust RSA Certification Authority",
    "USERTrust ECC Certification Authority",
    "Sectigo Public Server Authentication Root R46",
    "Sectigo Public Server Authentication Root E46",
)


def split_pem(text: str) -> list[str]:
    pattern = re.compile(
        r"-----BEGIN CERTIFICATE-----\s*(.*?)\s*-----END CERTIFICATE-----",
        re.S,
    )
    return [match.group(1) for match in pattern.finditer(text)]


def subject_name(der: bytes, index: int) -> str:
    with tempfile.NamedTemporaryFile(suffix=".der") as fh:
        fh.write(der)
        fh.flush()
        try:
            output = subprocess.check_output(
                [
                    "openssl",
                    "x509",
                    "-inform",
                    "DER",
                    "-noout",
                    "-subject",
                    "-nameopt",
                    "RFC2253",
                    "-in",
                    fh.name,
                ],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        except (OSError, subprocess.CalledProcessError):
            return f"Certificate {index + 1}"
    subject = output.removeprefix("subject=").strip()
    for part in subject.split(","):
        if part.startswith("CN="):
            return part[3:].replace(r"\,", ",").replace(r"\=", "=").strip()
    return subject or f"Certificate {index + 1}"


def const_ident(index: int) -> str:
    return f"ROOT_{index:03d}_DER"


def rust_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_der_array(der: bytes) -> str:
    lines: list[str] = []
    for offset in range(0, len(der), 16):
        chunk = der[offset : offset + 16]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {values},")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("bundle", nargs="?", help="PEM bundle path")
    parser.add_argument(
        "--out",
        default="src/tls_roots.rs",
        help="Rust output path, relative to repo root by default",
    )
    args = parser.parse_args()

    bundle = args.bundle
    if bundle is None:
        for candidate in DEFAULT_BUNDLES:
            if Path(candidate).exists():
                bundle = candidate
                break
    if bundle is None:
        raise SystemExit("no CA bundle found; pass a PEM bundle path")

    pem_path = Path(bundle)
    certs = []
    seen: set[str] = set()
    for index, pem_body in enumerate(split_pem(pem_path.read_text(errors="ignore"))):
        der = base64.b64decode("".join(pem_body.split()))
        fingerprint = hashlib.sha256(der).hexdigest()
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        certs.append(
            {
                "name": subject_name(der, index),
                "der": der,
                "fingerprint": fingerprint,
            }
        )

    order = {name: idx for idx, name in enumerate(PREFERRED_ROOTS)}
    certs.sort(key=lambda cert: (order.get(cert["name"], len(order)), cert["name"]))

    out = Path(args.out)
    rows = [
        "// Generated by scripts/generate_tls_roots.py; do not edit by hand.",
        f"// Source bundle: {pem_path}",
        "",
        "pub const TRUST_ROOTS: &[TrustRoot] = &[",
    ]
    for idx, cert in enumerate(certs):
        rows.append("    TrustRoot {")
        rows.append(f'        name: "{rust_string(cert["name"])}",')
        rows.append(f"        der: {const_ident(idx)},")
        rows.append("    },")
    rows.extend(
        [
            "];",
            "",
            "pub struct TrustRoot {",
            "    pub name: &'static str,",
            "    pub der: &'static [u8],",
            "}",
            "",
        ]
    )
    for idx, cert in enumerate(certs):
        rows.append(f"pub const {const_ident(idx)}: &[u8] = &[")
        rows.append(format_der_array(cert["der"]))
        rows.append("];")
        rows.append("")

    out.write_text("\n".join(rows))
    print(f"wrote {len(certs)} roots from {pem_path} to {out}")


if __name__ == "__main__":
    main()
